POC for generate-dist.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -132,6 +132,15 @@ jobs:
       - attach_workspace:
             at: .
       - run:
+          name: Verify ./view/frontend/web/js/checkout/dist directory does not exist
+          command: |
+            if [ -d "./view/frontend/web/js/checkout/dist" ]; then
+              echo "Directory ./view/frontend/web/js/checkout/dist exists. Failing the build."
+              exit 1
+            else
+              echo "Directory ./view/frontend/web/js/checkout/dist does not exist. Continuing."
+            fi
+      - run:
           name: PHPCS
           command: |
             ./vendor/bin/phpcs vendor/gene/module-better-checkout --standard=Magento2 --ignore=vendor,*.css,Test --extensions=php --colors -s -p -v --runtime-set installed_paths vendor/magento/magento-coding-standard,vendor/magento/php-compatibility-fork
